services:
  db:
    container_name: app-db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  app:
    container_name: app-api
    build: .
    command: >
      sh -c "python manage.py spectacular --color --file schema.yml &&
             python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
